### ISSUE TITLE
CoroutineMock doesn't seems to work with asyncio.run(asyncio.gather())

### ISSUE THREAD

**Issue by Natim** [Martiusweb/asynctest#114]
Any idea why this code doesn't work?

```
import asyncio
from asynctest import CoroutineMock

mocked_function = CoroutineMock()

asyncio.run(asyncio.gather(mocked_function()))
```

```
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    asyncio.run(asyncio.gather(mocked_function()))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 37, in run
    raise ValueError("a coroutine was expected, got {!r}".format(main))
ValueError: a coroutine was expected, got <_GatheringFuture pending>
```

**Comment by Natim** [comment]
I was able to reproduce with a simpler Mock:

```
import asyncio
from unittest.mock import Mock


class AsyncMock(Mock):

    def __call__(self, *args, **kwargs):
        sup = super(AsyncMock, self)
        async def coro():
            return sup.__call__(*args, **kwargs)
        return coro()

    def __await__(self):
        return self().__await__()

mocked_function = AsyncMock()

asyncio.run(asyncio.gather(mocked_function()))
```

**Comment by Natim** [comment]
If I use the following code, it seems to work:

```
import asyncio
from unittest.mock import Mock


class AsyncMock(Mock):

    def __call__(self, *args, **kwargs):
        sup = super(AsyncMock, self)
        async def coro():
            return sup.__call__(*args, **kwargs)
        return coro()

    def __await__(self):
        return self().__await__()

mocked_function = AsyncMock()

loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(mocked_function()))
```

**Comment by Natim** [comment]
I believe this might be a bug of Python itself: https://bugs.python.org/issue36222

**Comment by Natim** [comment]
It's a feature of run, that needs a coroutine while gather is returning a future.
