### ISSUE TITLE
Failing unit test

### ISSUE THREAD

**Issue by mdear** [Martiusweb/asynctest#86]
I downloaded the asynctest zipfile on Mar 14/2018 5:30P EDT, and found a failing unit test

[pyatsve_36] nostg-ott-vm-8:639> python setup.py test
running test
running egg_info
writing asynctest.egg-info/PKG-INFO
writing dependency_links to asynctest.egg-info/dependency_links.txt
writing top-level names to asynctest.egg-info/top_level.txt
reading manifest file 'asynctest.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'asynctest.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    setup(**args)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/ws/mdear-ott/pyats_36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/ws/mdear-ott/pyatsve_36/lib/python3.6/site-packages/setuptools/command/test.py", line 210, in run
    self.run_tests()
  File "/ws/mdear-ott/pyatsve_36/lib/python3.6/site-packages/setuptools/command/test.py", line 231, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/ws/mdear-ott/pyatsve_36/asynctest-master/asynctest/case.py", line 273, in run
    result.startTest(self)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/runner.py", line 54, in startTest
    self.stream.write(self.getDescription(test))
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/runner.py", line 47, in getDescription
    return '\n'.join((str(test), doc_first_line))
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/case.py", line 1383, in __str__
    self._testFunc.__name__)
AttributeError: 'str' object has no attribute '__name__'

**Comment by Martiusweb** [comment]
Some test files are missing in the last release (see issue #83).
setup.py test has never been configured, so I'm not sure if it works, usually I run tests with python -m unittest test.

**Comment by ernestask** [comment]
https://mail.python.org/pipermail/python-dev/2011-August/112738.html
