### ISSUE TITLE
asynctest / websocket tests 

### ISSUE THREAD

**Issue by mdear** [Martiusweb/asynctest#87]
I'm trying to uplift my asynctest-based tests from py34 to py35/36.

After receiving and implementing some suggestions in https://github.com/aaugustin/websockets/issues/359, I'm seeing new issues.

I'm finding that older asynctest (prior to 0.11) are showing a problem : AttributeError: '_UnixDefaultEventLoopPolicy' object has no attribute 'reset_watcher'

Commenting out the following lines allows my tests to pass as expected:
```
        if not self.use_default_loop:
            self.loop.close()
            #policy.reset_watcher()
        #asyncio.set_event_loop_policy(policy.original_policy)
```

And newer asynctest (0.11.0 and newer) are showing another problem:
RuntimeError: Event loop is closed

Any suggestions on how to resolve ?

 nostg-ott-vm-8:363> python -m unittest test_laas_async.TestVmCloudRest.test_websockets_1
```
E
======================================================================
ERROR: test_websockets_1 (test_laas_async.TestVmCloudRest)
Ensure reserve/create/delete/release requests are made as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ws/mdear-ott/pyatsve_36/lib/python3.6/site-packages/asynctest/case.py", line 186, in _unset_loop
    policy.reset_watcher()
AttributeError: '_UnixDefaultEventLoopPolicy' object has no attribute 'reset_watcher'

----------------------------------------------------------------------
Ran 1 test in 0.961s

FAILED (errors=1)
[pyatsve_36] nostg-ott-vm-8:364> python -m unittest test_laas_async.TestVmCloudRest.test_websockets_1
Traceback (most recent call last):
  File "/ws/mdear-ott/pyats_36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/ws/mdear-ott/pyatsve_36/lib/python3.6/site-packages/asynctest/case.py", line 302, in run
    self.loop.run_until_complete(self.doCleanups())
  File "/ws/mdear-ott/pyatsve_36/lib/python3.6/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "/ws/mdear-ott/pyats_36/lib/python3.6/asyncio/base_events.py", line 443, in run_until_complete
    self._check_closed()
  File "/ws/mdear-ott/pyats_36/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by mdear** [comment]
Closing issue, the "event loop closed" problem was on my end.  asynctest is working for me in py35/py36 now.
